image: "rust:latest"

stages:
  - test

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

cache:
  paths:
  - .cargo/
  - target/

test:
  stage: test
  artifacts:
    paths:
      - target/release/gluebuddy
  script:
    - cargo build --release --locked
    - cargo test --release --locked
