image: "rust:latest"

stages:
  - test

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

cache:
  paths:
  - .cargo/
  - target/

test:
  stage: test
  artifacts:
    paths:
      - target/release/gluebuddy
  script:
    - cargo build --release --locked
    - cargo test --release --locked

audit:
  stage: test
  before_script:
    - cargo install cargo-audit
  script:
    - cargo audit
      --ignore RUSTSEC-2020-0159 # `chrono` localtime_r segfault

clippy:
  stage: test
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --all -- -D warnings
